import type { Employee } from "../types/employeeTypes";

export const generateEmployees = (): Employee[] => {
  return [
    {
      id: '1',
      name: 'Maya Hawkee',
      designation: 'Founder and CEO',
      team: 'Operations',
      managerId: null,
      email: 'maya.hawkee@abcsolutions.com',
    },
    {
      id: '2',
      name: 'Steve Harrington',
      designation: 'Chief Technology Officer',
      team: 'Engineering',
      managerId: '1',
      email: 'steve.harrington@abcsolutions.com',
    },
    {
      id: '3',
      name: 'Lucas Sinclair',
      designation: 'Chief Product Officer',
      team: 'Product',
      managerId: '1',
      email: 'lucas.sinclair@abcsolutions.com',
    },
    {
      id: '4',
      name: 'Mike Wheeler',
      designation: 'Chief Business Officer',
      team: 'Sales',
      managerId: '1',
      email: 'mike.wheeler@abcsolutions.com',
    },
    {
      id: '5',
      name: 'Jane Cooper',
      designation: 'Engineering Manager',
      team: 'Engineering',
      managerId: '2',
      email: 'jane.cooper@abcsolutions.com',
    },
    {
      id: '6',
      name: 'Wade Warren',
      designation: 'Senior Software Engineer',
      team: 'Engineering',
      managerId: '5',
      email: 'wade.warren@abcsolutions.com',
    },
    {
      id: '7',
      name: 'Esther Howard',
      designation: 'Software Engineer',
      team: 'Engineering',
      managerId: '5',
      email: 'esther.howard@abcsolutions.com',
    },
    {
      id: '8',
      name: 'Guy Hawkins',
      designation: 'DevOps Engineer',
      team: 'Engineering',
      managerId: '2',
      email: 'guy.hawkins@abcsolutions.com',
    },
    {
      id: '9',
      name: 'Erica',
      designation: 'Product Manager',
      team: 'Product',
      managerId: '3',
      email: 'erica@abcsolutions.com',
    },
    {
      id: '10',
      name: 'Nancy Wheeler',
      designation: 'Product Manager',
      team: 'Product',
      managerId: '3',
      email: 'nancy.wheeler@abcsolutions.com',
    },
    {
      id: '11',
      name: 'Jenny Wilson',
      designation: 'UX Designer',
      team: 'Product',
      managerId: '9',
      email: 'jenny.wilson@abcsolutions.com',
    },
    {
      id: '12',
      name: 'Jacob Jones',
      designation: 'UI Designer',
      team: 'Product',
      managerId: '9',
      email: 'jacob.jones@abcsolutions.com',
    },
    {
      id: '13',
      name: 'Ronald Richards',
      designation: 'Sales Director',
      team: 'Sales',
      managerId: '4',
      email: 'ronald.richards@abcsolutions.com',
    },
    {
      id: '14',
      name: 'Devon Lane',
      designation: 'Account Executive',
      team: 'Sales',
      managerId: '13',
      email: 'devon.lane@abcsolutions.com',
    },
    {
      id: '15',
      name: 'Jerome Bell',
      designation: 'Sales Representative',
      team: 'Sales',
      managerId: '13',
      email: 'jerome.bell@abcsolutions.com',
    },
    {
      id: '16',
      name: 'Dustin Henderson',
      designation: 'Marketing Director',
      team: 'Marketing',
      managerId: '1',
      email: 'dustin.henderson@abcsolutions.com',
    },
    {
      id: '17',
      name: 'Robin Buckley',
      designation: 'Content Manager',
      team: 'Marketing',
      managerId: '16',
      email: 'robin.buckley@abcsolutions.com',
    },
    {
      id: '18',
      name: 'Max Mayfield',
      designation: 'Social Media Manager',
      team: 'Marketing',
      managerId: '16',
      email: 'max.mayfield@abcsolutions.com',
    },
    {
      id: '19',
      name: 'Jim Hopper',
      designation: 'Chief Financial Officer',
      team: 'Finance',
      managerId: '1',
      email: 'jim.hopper@abcsolutions.com',
    },
    {
      id: '20',
      name: 'Joyce Byers',
      designation: 'Finance Manager',
      team: 'Finance',
      managerId: '19',
      email: 'joyce.byers@abcsolutions.com',
    },
  ];
};